# Generated by Django 3.0.5 on 2020-05-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album',
            new_name='artist',
        ),
    ]
